### PR TITLE
Merge branch columnstore-22.08.8-1 into develop-22.08

### PR DESCRIPTION
**Pull request by tntnatbry**

### CODE REVIEW

**Review by drrtuy — DISMISSED** [review]

**Comment by drrtuy** [comment]
Before we merge could you double check regr test001 failure produced by this merge @tntnatbry ?

**Comment by tntnatbry** [comment]
@drrtuy The following test001 test has failed:

```bash
tntnatbry@tntnatbry:~/Downloads/archive/2023-02-20@09:39:45$ diff -w working_tpch1_compareLogOnly/view/mts_view.40.sql.log working_tpch1_compareLogOnly/view/mts_view.40.sql.ref.log 
1,5c1,5
< ERROR 1815 (HY000) at line 130: Internal error: MCS-3012: Scalar filter and semi join are not from the same pair of tables.
< ERROR 1815 (HY000) at line 135: Internal error: MCS-3012: Scalar filter and semi join are not from the same pair of tables.
< ERROR 1815 (HY000) at line 144: Internal error: MCS-3012: Scalar filter and semi join are not from the same pair of tables.
< ERROR 1815 (HY000) at line 149: Internal error: MCS-3012: Scalar filter and semi join are not from the same pair of tables.
< ERROR 1815 (HY000) at line 160: Internal error: MCS-3012: Scalar filter and semi join are not from the same pair of tables.
---
> ERROR 1815 (HY000) at line 130: Internal error: MCS-3033: Correlated subquery within OR operator is currently not supported.
> ERROR 1815 (HY000) at line 135: Internal error: MCS-3033: Correlated subquery within OR operator is currently not supported.
> ERROR 1815 (HY000) at line 144: Internal error: MCS-3033: Correlated subquery within OR operator is currently not supported.
> ERROR 1815 (HY000) at line 149: Internal error: MCS-3033: Correlated subquery within OR operator is currently not supported.
> ERROR 1815 (HY000) at line 160: Internal error: MCS-3033: Correlated subquery within OR operator is currently not supported.
```
I find this failure strange as the 4 commits in this merge do not change the SQL funtionality.

**Comment by drrtuy** [comment]
Plz double check the regr branch used running the test.
JFYI @denis0x0D recently made join-related changes that alters the error message returned so he updated this test in develop of the regr repo. However this must not affect develop-22.08.

**Comment by tntnatbry** [comment]
@drrtuy Regression test repo branch used for this PR is develop. I see that @denis0x0D updated the mts_view.40.sql.ref.log reference file in develop. However, develop-22.08 does not have the fix for MCOL-5195. This explains why this test failed on develop-22.08. Do you guys know why this failure is not caught in the develop-22.08 nightly builds?

**Comment by drrtuy** [comment]
I think 22.08 uses develop regr in its ci description.
I asked Roman to change this.

**Review by drrtuy — APPROVED** [review]
CI used a wrong branch to test this merge patch.

**Comment by drrtuy** [comment]
Plz tag the merge commit @tntnatbry .

**Comment by tntnatbry** [comment]
@drrtuy Done. I have created v-columnstore-22.08.8-1 with this merge commit. One thing to note here, the PR: https://github.com/mariadb-corporation/mariadb-columnstore-engine/pull/2718

This PR was merged into develop-22.08 before columnstore-22.08.8 was merged. Now when I created the v-columnstore-22.08.8-1 tag, it also contains the above PR. So this tag is not really just the 22.08.8 release. In future, we should not be merging any new code to develop-<22.x> branch before merging the columnstore-<22.x> release branch into develop-<22.x>. Basically, the develop-<22.x> branch should be frozen for new PR merges (creating new PRs should be allowed) until the release merge commit is performed.

**Pull request merged**
