### PR TITLE
MCOL-5519: new defaults in columnstore.cnf

### PR DESCRIPTION
**Pull request by mariadb-AlexeyVorovich**

### CODE REVIEW

**Review by drrtuy — CHANGES_REQUESTED** [review]
The engine must do this default change and not an engine.

**Comment by toddstoffel** [comment]
This is a product management decision. Please proceed with changes.

**Review by mariadb-LeonidFedorov — APPROVED** [review]

**Review by mariadb-LeonidFedorov — CHANGES_REQUESTED** [review]
This changes causes failures of regressions tests, and this test must be fixed accordingly

**Comment by mariadb-AlexeyVorovich** [comment]
@mariadb-DanielLee .. Please see the MTR fixes committed by Leonid. Please make the same type of changes in regression

**Comment by mariadb-LeonidFedorov** [comment]
Same types of changes are not relevant here. I removed the hacks of starting tests, but tests itself should be fixed

**Review by mariadb-LeonidFedorov — APPROVED** [review]

**Review by drrtuy — APPROVED** [review]

**Pull request merged**
