### PR TITLE
[MCOL-4849] Fix build warnings.

### PR DESCRIPTION
**Pull request by denis0x0D**

### CODE REVIEW

**Comment by denis0x0D** [comment]
Unfortunately I've introduced some warnings in MCOL-4849, this is a fix for them.

**Review by davidhall586 — CHANGES_REQUESTED** [review]
I incorporated these warning changes in my PR for MCOL-4841. If we merge this, then there will be merge conflicts

**Comment by denis0x0D** [comment]
@dhall-MariaDB sure, I'll rebase it on your work.

**Comment by drrtuy** [comment]
David's patch needs a little more attention so I merge this patch.

**Review by drrtuy — APPROVED** [review]

**Pull request merged**
