### PR TITLE
fix compilation of 6.x in gcc 13.2.1

### PR DESCRIPTION
**Pull request by vuvova**

### CODE REVIEW

**Comment by drrtuy** [comment]
You should reopen the PR against develop-6 b/c[ our CI complains](https://ci.columnstore.mariadb.net/mariadb-corporation/mariadb-columnstore-engine/9326) about unrelated history.

**Comment by vuvova** [comment]
it is against develop-6 already

**Comment by drrtuy** [comment]
It is but you changed the PR target branch and this drives CI mad.

**Comment by drrtuy** [comment]
I'll re-create it.

**Pull request closed without merging**
