### PR TITLE
MCS6 compilation issue

### PR DESCRIPTION
**Pull request by drrtuy**
This is a backport of a set of fixes for newer compilers

### CODE REVIEW

**Comment by vuvova** [comment]
I cannot review that :(
do 300+ files with comment changes have to be in the same commit as the actual compilation fix?
if yes, tell me what change in what file to review and I'll do just that.

**Comment by drrtuy** [comment]
> I cannot review that :( do 300+ files with comment changes have to be in the same commit as the actual compilation fix? if yes, tell me what change in what file to review and I'll do just that.[

[rowestimator.cpp](https://github.com/mariadb-corporation/mariadb-columnstore-engine/pull/3169/files#diff-91995d72234595481422ad8fcb49c66bd32dbf86fb4bc1773df48ff35a45815d)

**Comment by vuvova** [comment]
`rowestimator.cpp` change is
```diff
--- a/dbcon/joblist/rowestimator.cpp
+++ b/dbcon/joblist/rowestimator.cpp
@@ -269,8 +269,8 @@ float RowEstimator::estimateRowReturnFactor(const BRM::EMEntry& emEntry, const m
   float tempFactor = 1.0;
 
   uint64_t adjustedMin = 0, adjustedMax = 0;
-  uint128_t adjustedBigMin, adjustedBigMax;
-  uint32_t distinctValuesEstimate;
+  uint128_t adjustedBigMin = 0, adjustedBigMax = 0;
+  uint32_t distinctValuesEstimate = 0;
 
   // Adjust values based on column type and estimate the
   if (!ct.isWideDecimalType())
```
which looks obviously safe. At least not worse than it was before. It'll shut up the compiler warning, for sure. But I cannot say if there was a bug that compiler warned you about or not. That is, if you needed to fix the bug or just shut up the compiler.

**Comment by drrtuy** [comment]
> `rowestimator.cpp` change is
> 
> ```diff
> --- a/dbcon/joblist/rowestimator.cpp
> +++ b/dbcon/joblist/rowestimator.cpp
> @@ -269,8 +269,8 @@ float RowEstimator::estimateRowReturnFactor(const BRM::EMEntry& emEntry, const m
>    float tempFactor = 1.0;
>  
>    uint64_t adjustedMin = 0, adjustedMax = 0;
> -  uint128_t adjustedBigMin, adjustedBigMax;
> -  uint32_t distinctValuesEstimate;
> +  uint128_t adjustedBigMin = 0, adjustedBigMax = 0;
> +  uint32_t distinctValuesEstimate = 0;
>  
>    // Adjust values based on column type and estimate the
>    if (!ct.isWideDecimalType())
> ```
> 
> which looks obviously safe. At least not worse than it was before. It'll shut up the compiler warning, for sure. But I cannot say if there was a bug that compiler warned you about or not. That is, if you needed to fix the bug or just shut up the compiler.

The patch is a backport so you don't need to worry about this part. You are involved so I need a green light from you to satisfy the rules.

**Review by mariadb-DenisKhalikov — APPROVED** [review]
LGTM

**Pull request merged**
