### PR TITLE
MCOL-2102 postConfigure -port now changes CrossEngineSupport Port

### PR DESCRIPTION
**Pull request by jmrojas2332**
Set CrossEngineSupport Port number when setting MySQLPort via postConfigure -port

### CODE REVIEW

**Comment by jmrojas2332** [comment]
Submitting this under the 3-clause BSD license.

**Comment by drrtuy** [comment]
Greetings. We appreciate the contribution. There are some failures in our CI tests so we will look into them and get back shortly.

**Review by drrtuy — APPROVED** [review]

**Comment by drrtuy** [comment]
The failure is irrelevant so I merged the patch.

**Comment by jmrojas2332** [comment]
Awesome. Thanks.

**Pull request merged**
