### PR TITLE
Fixes MCOL-4511 and MCOL-4524

### PR DESCRIPTION
**Pull request by zhaorenhai**

### CODE REVIEW

**Comment by drrtuy** [comment]
The failed MTR test contains a mistake in the reference file.

**Review by drrtuy — APPROVED** [review]

**Comment by drrtuy** [comment]
@zhaorenhai Could you confirm that you contribute this under BSL?

**Comment by zhaorenhai** [comment]
Yes, I can confirm

**Comment by zhaorenhai** [comment]
Sorry, Roman, 'The failed MTR test contains a mistake in the reference file.' 
Is it related with my commits?

**Comment by drrtuy** [comment]
No, it doesn't at all.
Thank you for the contribution!

вс, 31 янв. 2021 г., 4:20 zhaorenhai <notifications@github.com>:

**Pull request merged**
