### PR TITLE
Logging of memory 

### PR DESCRIPTION
**Pull request by mariadb-AlexeyVorovich**
this is incomplete.  I am doing this to have drone create the package so that I can test docker

### CODE REVIEW

**Comment by mariadb-AlexeyVorovich** [comment]
@mariadb-LeonidFedorov  @drrtuy  I am trying to improve logging for total and available memory for both cgroup and non-cgroup. Question :
getFreeMemory is called on timer . The current version does inconsistent logging 
-for cgroup (I see that in container) each call  is logged
-for non-cgroup (i see in VM) no calls are logged
I added logging to both places in this PR . However this creates unreadable huge logs. What do you want to do ? remove logging from both cases ? make it depend on setting ? other suggestions ?

**Comment by mariadb-AlexeyVorovich** [comment]
printing msg on every invocation clearly makes the primproc log unusable.  So it cannot stay.

I did notice that in pure develop (without my PR)  i get 1k messages
Aug 23 15:41:43 av2 env[169323]: [140B blob data]
Aug 23 15:41:43 av2 env[169323]: [140B blob data]

**Comment by mariadb-AlexeyVorovich** [comment]
log each 1000 call per LF. effectively 15min

**Comment by drrtuy** [comment]
The size of a log was a reason why I removed logging from getFreeMemory in the first place.
IMHO one-shot logging that is now presented is useful. One can see the amount of RAM on startup. You can prettify it printing outGBs instead of byte units.

**Comment by mariadb-AlexeyVorovich** [comment]
- The GB printout at start is in PR 
- getfreememory was inconsistent  (with logging for cgroup and w/o logging for no cgroup). per LF , i made it  every 1000 calls or effectively 15 min at current polling rate.  Please decide if ongoing mem diagnostic is useful or should I comment it out 

Let me know 

@mariadb-LeonidFedorov  make the decision on above , pls

**Review by mariadb-LeonidFedorov — APPROVED** [review]

**Pull request merged**
