### PR TITLE
MCOL-3982 Avoid using autotools for libmarias3 and remove libxml2 fro…

### PR DESCRIPTION
**Pull request by drrtuy**
…m libmarias3 dependencies.

### CODE REVIEW

**Review by pleblanc1976 — APPROVED** [review]

**Comment by pleblanc1976** [comment]
Waiting on the end of the freeze on dev-1.4

**Review by pleblanc1976 — CHANGES_REQUESTED** [review]
Dave is telling me this broke the build on his C7 machine, with the error msg:
```
/home/calpont/mariadb/engine/utils/libmarias3/libmarias3/src/debug.c:20:20: fatal error: config.h: No such file or directory
 #include "config.h"
```
That file is generated by autoconf so it makes sense that it would be missing.  I'm not sure why the C7 PR builder succeeded though.  Getting the wrong PR code?  Is it finding another config.h?  Need to follow up.  Will need to follow up with 1.5 also.

**Comment by drrtuy** [comment]
B/c BB follows the way ENT builders use to produce packages, namely it builds MCS having it under storage/columnstore. Server team builds libmarias3 for ARIA engine also. Building the engine this way compiler finds config.h in MDB_SRC/include.
JFYI David builds it out-of-source as we did in 1.2 era.

**Review by pleblanc1976 — APPROVED** [review]
Tentatively thinking this is OK

**Comment by pleblanc1976** [comment]
This might be a workaround for a weird SLES 15 build problem we're having in Jenkins.  It's failing with the error 
`checking C++ Compiler version... /home/jenkins/workspace/10.4e-RPM-DEV/label/sles-15/padding_for_CPACK_RPM_BUILD_SOURCE_DIRS_PREFIX_ON_ES_BACKUP_DEBUGSOURCE/storage/columnstore/columnstore/utils/libmarias3/libmarias3/configure: line 13400: --version: command not found`

... as if it's trying to execute '--version' instead of 'g++ --version'.  IDK if this will break out-of-source builds, but we can fix that if necessary afterward.

**Pull request merged**
