### PR TITLE
fix to possible memory corruption

### PR DESCRIPTION
**Pull request by ghost**
b >> reinterpret_cast< ByteStream::doublebyte&>(fAsc); casts a byte to a short so two bytes get written to fAsc.

### CODE REVIEW

**Comment by davidhall586** [comment]
I think it would be a better solution to add bool as a supported type to bytestream, rather than make a copy like this. Using sizeof(bool), we could determine the proper number of bytes to move into the stream.

**Comment by drrtuy** [comment]
ByteStream divides supported data types in floats and ints future dividing ints by width so I would just use byte + cast instead in ser/des functions.

**Comment by ghost** [comment]
> I think it would be a better solution to add bool as a supported type to bytestream, rather than make a copy like this. Using sizeof(bool), we could determine the proper number of bytes to move into the stream.

I began removing all the overloads and creating a handful of specializations. One implementation handled POD while a few other handled containers. This exposed a couple bigger problems with the bytestream implementation that need to be addressed. I don't want to add to the pile right now.

**Comment by davidjmott** [comment]
This is a fix for a memory corruption bug.

**Review by davidhall586 — APPROVED** [review]

**Pull request merged**
