### PR TITLE
Generate published package URL as part of new pipeline step

### PR DESCRIPTION
**Pull request by Zulu-Inuoe**
Hi @mariadb-LeonidFedorov, sorry for the delay on this one.

I'm marking this one as a draft because I have not had a chance to yet test this. I did some digging with regards to getting clickable URL's somewhere in the pipeline output, and using ANSI escape codes for links is the closest I've found. However, I've read conflicting information about whether or not this'll work when run under Drone CI.

There's some information in the thread here <https://community.harness.io/t/add-custom-links-to-build-page/10087/3>

I'd like to test this locally, but that involves setting up a drone instance and I haven't found the time yet to do so.
I'd appreciate any thoughts. Note that there's duplication of the expression there but I'm more curious to know if it even works. It can get moved up to a variable.

I'd appreciate your thoughts

### CODE REVIEW

**Comment by Zulu-Inuoe** [comment]
Oh hey, I wasn't sure if you had builds enabled on PR's.

If you travel to eg <https://ci.columnstore.mariadb.net/mariadb-corporation/mariadb-columnstore-engine/7359/7/8>, it looks like indeed, Drone CI does produce a clickable link.

I'll dump this in a variable and add the missing depends_on

**Review by mariadb-LeonidFedorov — APPROVED** [review]

**Comment by mariadb-LeonidFedorov** [comment]
@Zulu-Inuoe Perfect solution! Do you mind me merging this PR to main code branch?

**Comment by Zulu-Inuoe** [comment]
Great to hear! And not at all, go right ahead if you're happy with it

**Comment by mariadb-LeonidFedorov** [comment]
@Zulu-Inuoe Thanks! Very appreciated

**Pull request merged**
