### PR TITLE
[MCOL-4778] Return if we have an error in push_down_init.

### PR DESCRIPTION
**Pull request by denis0x0D**

### CODE REVIEW

**Review by tntnatbry — CHANGES_REQUESTED** [review]
LGTM. However, the crashing SQL test case should be added to MTR.

**Comment by denis0x0D** [comment]
@tntnatbry in which part of mtr we adding tests cases for this kind of bugs `basics` or something else?

**Comment by tntnatbry** [comment]
@denis0x0D Since this is a bug fix, we can put it under `mysql-test/columnstore/bugfixes/`.

**Comment by denis0x0D** [comment]
@tntnatbry, I see, thanks!

**Review by davidhall586 — APPROVED** [review]

**Review by tntnatbry — APPROVED** [review]

**Pull request merged**
