### PR TITLE
fix compilation with gcc 13.2.1

### PR DESCRIPTION
**Pull request by drrtuy**

### CODE REVIEW

**Comment by drrtuy** [comment]
@vuvova There is [an issue](https://ci.columnstore.mariadb.net/mariadb-corporation/mariadb-columnstore-engine/9329/2/4) compiling this patch.
 ```
/mdb/verylongdirnameforverystrangecpackbehavior/storage/columnstore/columnstore/storage-manager/src/LocalStorage.cpp: In member function 'int storagemanager::LocalStorage::copy(const boost::filesystem::path&, const boost::filesystem::path&)':

/mdb/verylongdirnameforverystrangecpackbehavior/storage/columnstore/columnstore/storage-manager/src/LocalStorage.cpp:97:35: error: 'bf::copy_options' has not been declared

   97 |   bf::copy_file(source, dest, bf::copy_options::none, err);

      |                                   ^~~~~~~~~~~~

make[2]: *** [storage/columnstore/columnstore/storage-manager/CMakeFiles/storagemanager.dir/build.make:342: storage/columnstore/columnstore/storage-manager/CMakeFiles/storagemanager.dir/src/LocalStorage.cpp.o] Error 1
```

**Comment by vuvova** [comment]
There's an alternative — more
```
 #pragma GCC diagnostic ignored "-Wdeprecated-declarations"
```
May be you want it in a `CMakeLists.txt` instead and not sprinkled all over the sources?

**Comment by mariadb-LeonidFedorov** [comment]
> There's an alternative — more
> 
> ```
>  #pragma GCC diagnostic ignored "-Wdeprecated-declarations"
> ```
> 
> May be you want it in a `CMakeLists.txt` instead and not sprinkled all over the sources?

Funny thing, we have it in CMakeLists.txt for 23.10
```
MY_CHECK_AND_SET_COMPILER_FLAG("-Wno-deprecated-copy" DEBUG RELEASE RELWITHDEBINFO MINSIZEREL)
MY_CHECK_AND_SET_COMPILER_FLAG("-Wno-deprecated-declarations" DEBUG RELEASE RELWITHDEBINFO MINSIZEREL)
```
So, I'm pretty OK to set it for develop-6

**Comment by vuvova** [comment]
ok, done

**Comment by mariadb-LeonidFedorov** [comment]
> ok, done
```
/mdb/verylongdirnameforverystrangecpackbehavior/storage/columnstore/columnstore/storage-manager/src/Ownership.cpp:80:18: error: 'class boost::filesystem::path' has no member named 'lexically_normal'
   normalizedPath.lexically_normal();
```
This does not build on centos 7. Columnstore-6 depends on system boost, that was replaced by embedded one in next versions to avoid this pain

**Review by mariadb-LeonidFedorov — APPROVED** [review]

**Pull request merged**
