### PR TITLE
Mcol 271 empty strings should not be nulls

### PR DESCRIPTION
**Pull request by mariadb-SergeyZefirov**
Huge changeset that touches almost everything.

Main idea was to introduce standalone type NullString to hold a string that can be NULL (nullptr) and then work things out from copiler errors.

It was successful up to a point - there are places in our code where values are accompanied by the boolean flag isNull. This is true for funcexp and for some other places.

Thus, there are two ideas there.

Still, the need to address the absence of default conversion between NullString and std::string allowed to uncover most of the problematic places.

Right now code is not rebased because of the Windows borked my repository (inside WSL2 VM, no less). I will address issues and rebase it. And then address some other issues.

There are places where changes are not all that meaningful at first sight - e.g., braces are added around a statement under if condition, etc. This is so because this statement under condition required investigation and, probably, to leave statement better isolated is to better serve engineers after us.

The test for that particular task is rather short, but other tests were affected and I made my best to make sure we are as close to MyISAM/InnoDB as we can be there.

### CODE REVIEW

**Comment by mariadb-LeonidFedorov** [comment]
Let's fix unittests first, then look at mtr and regression

**Comment by mariadb-SergeyZefirov** [comment]
> Let's fix unittests first, then look at mtr and regression

You would not believe it, but I have unit-tests fixed in my branch: https://github.com/mariadb-SergeyZefirov/mariadb-columnstore-engine/blob/MCOL-271-empty-strings-should-not-be-null/tests/rowgroup-tests.cpp#L93

Most crucial difference is this:

``columnstore/columnstore/tests$ git diff develop rowgroup-tests.cpp
diff --git a/tests/rowgroup-tests.cpp b/tests/rowgroup-tests.cpp
index 0c2a2e789..5d8cbbd51 100644
--- a/tests/rowgroup-tests.cpp
+++ b/tests/rowgroup-tests.cpp
@@ -90,6 +90,9 @@ class RowDecimalTest : public ::testing::Test

     rg.initRow(&r);
     rg.initRow(&rOutMappingCheck);
+    rg.initRow(&rOut);
+    rg.initRow(&sameRow);
+    rg.initRow(&nonequiRow);
     rowSize = r.getSize();
     rg.getRow(0, &r);
``

But I cannot see it in the changeset.

So, believe me, I have unittests and MTR green. Can you please look at this monstrous thing while I dance around infrastructure beating my trusty tambourine?

**Comment by mariadb-SergeyZefirov** [comment]
As a matter of fact, regression requires specific branch: https://github.com/mariadb-corporation/mariadb-columnstore-regression-test/tree/MCOL-271-empty-strings-should-not-be-nulls

There are a lot of "empty string is expected to be NULL" results fixed.

**Comment by mariadb-SergeyZefirov** [comment]
It won't merge anyway.

**Pull request closed without merging**
