### PR TITLE
CI from develop + cmapi [develop-23.02]

### PR DESCRIPTION
**Pull request by mariadb-LeonidFedorov**
This patch do not try no merge .drone.jsonnet from original PR, but replaces it with develop version.
scripts used by CI were also replaced with develop versions
Let's see the builds result

### CODE REVIEW

**Comment by tntnatbry** [comment]
@mariadb-LeonidFedorov It looks like test001/test000 failed for Centos7 and Ubuntu20.

**Review by mariadb-AlanMologorsky — APPROVED** [review]
LGTM
Builds seems to be ok, except centos7 and ubuntu20.
The reason is in missed `./regression_logs.sh` file.

**Review by mariadb-RomanNavrotskiy — APPROVED** [review]

**Comment by mariadb-LeonidFedorov** [comment]
@tntnatbry the only test that fails is multinode MTR on rocky 8

**Review by drrtuy — APPROVED** [review]
There are two points regarding the patch that must be addressed ASAP IMHO:
- license should be less restrictive
- engine_files dir is obsolete and misguiding so must be deleted

**Pull request merged**
