### PR TITLE
MCOL-5709: Duplicate stable-23.10

### PR DESCRIPTION
**Pull request by mariadb-AlanMologorsky**
Duplicate from #3179 + fix conflicts.
Refactor save_brm to store BRM snapshot localy firstly and then remotely: S3, NFS etc.

### CODE REVIEW

**Comment by drrtuy** [comment]
I agree with all changes but I want to see the commits squashed before we proceed.

**Review by drrtuy — APPROVED** [review]
ACK

**Comment by drrtuy** [comment]
This PR needs a rebase b/c all CI build pipelines are failing.

**Comment by mariadb-AlanMologorsky** [comment]
> This PR needs a rebase b/c all CI build pipelines are failing.

Confused - it was rebased already.

**Pull request merged**
