### PR TITLE
MCOL-537 Regression test doesn't tolerate 'failed' in stderr, stdout.

### PR DESCRIPTION
**Pull request by drrtuy**
I reformulate the messages.

    Changed version in preprocessor conditions to avoid compilation
    warnings in Debian 9.

    Disabled sign-compare check for generated files in DML/DDL.

### CODE REVIEW

**Review by pleblanc1976 — CHANGES_REQUESTED** [review]
There are still a couple distros it's failing to compile on.  I would suggest separating the issues.  This ticket only requires changing the 'failed' text, which would be easy & quick.  I'd open another ticket for the remaining compiler warnings and get to that when you have spare time (HA!).

**Comment by drrtuy** [comment]
Centos 6 fails b/c we stoped to support it when enabled C++11, U16 fails b/c of the failed API test - Mcol1408. Andrew promiced to look into this. Windows build complains about non-absolute paths for mcsimport.

**Comment by LinuxJedi** [comment]
We should remove develop from the CentOS 6 builder. I will indeed look into the MCOL-1408 regression soon.

**Review by pleblanc1976 — APPROVED** [review]
Ok will approve & merge & etc.

**Pull request merged**
